<a href="https://colab.research.google.com/github/kushal2022/Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic PyTorch

In [2]:
import torch

weights = torch.tensor([0.2126, 0.7152, 0.0722], requires_grad=True)

for epoch in range(10):
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])


In [4]:
weights = torch.tensor([0.2126, 0.7152, 0.0722], requires_grad=True)

# Wrap the weights tensor in a list to make it an iterable
optimizer = torch.optim.SGD([weights], lr=0.01)

for epoch in range(10):
  model_output = (weights * 3).sum()

  model_output.backward()

  print(weights.grad)

  optimizer.step()

  optimizer.zero_grad()

tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])
tensor([3., 3., 3.])


**Back propagation example with pytorch**

In [5]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

# backward pass
loss.backward()
print(w.grad)

### update weights
### next forward and backward

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
